// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/compilador/Lexico.flex

/* =====================================================================
   Teoría de la Computación I - UNLu
   Trabajo Práctico Integrador - Compilador 2026
   Grupo 7 - Tema especial: APLICARDESCUENTO
   Primera entrega: analizador léxico
   ===================================================================== */

package compilador;


@SuppressWarnings("fallthrough")
public class Lexico {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int COMENTARIO = 2;
  public static final int COMENTARIO_ANIDADO = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2, 2
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\0\1\2\22\0\1\1\1\3"+
    "\1\4\5\0\1\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\12\15\1\16\1\17\1\20\1\21\1\22"+
    "\2\0\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\2\24\1\34\1\35\1\36\1\37\1\40"+
    "\1\24\1\41\1\42\1\43\1\44\1\24\1\45\3\24"+
    "\1\46\1\0\1\47\1\0\1\50\1\0\4\24\1\51"+
    "\3\24\1\52\10\24\1\53\1\24\1\54\2\24\1\55"+
    "\3\24\1\56\1\0\1\57\43\0\1\60\57\0\1\60"+
    "\37\0\1\60\u010e\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\1\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\1\1\12\1\13\1\1\1\14"+
    "\1\15\1\1\1\16\13\17\1\20\1\21\1\17\1\22"+
    "\1\23\5\24\1\25\1\3\1\0\1\26\1\0\1\27"+
    "\2\0\1\30\1\31\1\32\1\33\1\0\6\17\1\34"+
    "\1\17\1\35\6\17\4\0\1\36\1\37\1\40\1\41"+
    "\1\42\5\17\1\43\6\17\1\44\1\45\1\46\1\47"+
    "\2\17\1\50\7\17\1\51\6\17\1\52\2\17\1\53"+
    "\2\17\1\54\1\55\6\17\1\56\7\17\1\0\2\17"+
    "\1\57\1\0\1\17\1\0\2\17\1\0\1\17\1\0"+
    "\2\17\1\0\1\17\4\0\1\17\4\0\1\17\4\0"+
    "\1\17\4\0\1\17\1\60\2\0\1\61\1\62\4\0"+
    "\1\63\1\64";

  private static int [] zzUnpackAction() {
    int [] result = new int[181];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\142\0\223\0\304\0\365\0\u0126\0\223"+
    "\0\223\0\u0157\0\223\0\223\0\223\0\u0188\0\u01b9\0\u01ea"+
    "\0\u021b\0\223\0\u024c\0\u027d\0\u02ae\0\u02df\0\u0310\0\u0341"+
    "\0\u0372\0\u03a3\0\u03d4\0\u0405\0\u0436\0\u0467\0\u0498\0\u04c9"+
    "\0\223\0\223\0\u04fa\0\223\0\223\0\223\0\u052b\0\u055c"+
    "\0\u058d\0\u05be\0\223\0\u05ef\0\u0620\0\223\0\u0651\0\u0188"+
    "\0\u0682\0\u06b3\0\223\0\223\0\223\0\223\0\u0310\0\u06e4"+
    "\0\u0715\0\u0746\0\u0777\0\u07a8\0\u07d9\0\u0310\0\u080a\0\u0310"+
    "\0\u083b\0\u086c\0\u089d\0\u08ce\0\u08ff\0\u0930\0\u0961\0\u0992"+
    "\0\u09c3\0\u09f4\0\223\0\223\0\223\0\223\0\u0310\0\u0a25"+
    "\0\u0a56\0\u0a87\0\u0ab8\0\u0ae9\0\u0310\0\u0b1a\0\u0b4b\0\u0b7c"+
    "\0\u0bad\0\u0bde\0\u0c0f\0\223\0\223\0\223\0\223\0\u0c40"+
    "\0\u0c71\0\u0310\0\u0ca2\0\u0cd3\0\u0d04\0\u0d35\0\u0d66\0\u0d97"+
    "\0\u0dc8\0\u0310\0\u0df9\0\u0e2a\0\u0e5b\0\u0e8c\0\u0ebd\0\u0eee"+
    "\0\u0310\0\u0f1f\0\u0f50\0\u0310\0\u0f81\0\u0fb2\0\u0310\0\u0310"+
    "\0\u0fe3\0\u1014\0\u1045\0\u1076\0\u10a7\0\u10d8\0\u0310\0\u1109"+
    "\0\u113a\0\u116b\0\u119c\0\u11cd\0\u11fe\0\u122f\0\u1260\0\u1291"+
    "\0\u12c2\0\u0310\0\u12f3\0\u1324\0\u1355\0\u1386\0\u13b7\0\u13e8"+
    "\0\u1419\0\u144a\0\u147b\0\u14ac\0\u14dd\0\u150e\0\u153f\0\u1570"+
    "\0\u15a1\0\u15d2\0\u1603\0\u1634\0\u1665\0\u1696\0\u16c7\0\u16f8"+
    "\0\u1729\0\u175a\0\u178b\0\u17bc\0\u17ed\0\u181e\0\u184f\0\u1880"+
    "\0\u18b1\0\u18e2\0\223\0\u1913\0\u1944\0\223\0\u0310\0\u1975"+
    "\0\u19a6\0\u19d7\0\u1a08\0\223\0\223";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[181];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\2\5\1\6\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\2\27\1\30\1\31\1\32\2\27"+
    "\1\33\3\27\1\34\1\35\1\27\1\36\1\37\1\27"+
    "\1\40\1\41\1\42\1\4\4\27\1\43\1\44\1\45"+
    "\1\4\7\46\1\47\4\46\1\50\53\46\1\51\4\46"+
    "\1\52\44\46\62\0\2\5\77\0\1\53\37\0\1\54"+
    "\1\7\1\55\1\7\1\56\2\54\37\7\3\54\5\7"+
    "\2\54\1\7\14\0\1\57\61\0\1\60\57\0\1\61"+
    "\57\0\1\60\1\0\1\20\61\0\1\62\2\0\1\63"+
    "\60\0\1\64\60\0\1\65\60\0\1\66\51\0\1\67"+
    "\2\0\1\27\5\0\13\27\1\70\1\27\1\71\5\27"+
    "\2\0\1\67\5\27\15\0\1\67\2\0\1\27\5\0"+
    "\23\27\2\0\1\67\5\27\15\0\1\67\2\0\1\27"+
    "\5\0\4\27\1\72\16\27\2\0\1\67\5\27\15\0"+
    "\1\67\2\0\1\27\5\0\11\27\1\73\1\27\1\74"+
    "\7\27\2\0\1\67\5\27\15\0\1\67\2\0\1\27"+
    "\5\0\11\27\1\75\11\27\2\0\1\67\5\27\15\0"+
    "\1\67\2\0\1\27\5\0\5\27\1\76\5\27\1\77"+
    "\7\27\2\0\1\67\5\27\15\0\1\67\2\0\1\27"+
    "\5\0\16\27\1\100\4\27\2\0\1\67\5\27\15\0"+
    "\1\67\2\0\1\27\5\0\16\27\1\101\4\27\2\0"+
    "\1\67\5\27\15\0\1\67\2\0\1\27\5\0\20\27"+
    "\1\102\2\27\2\0\1\67\5\27\15\0\1\67\2\0"+
    "\1\27\5\0\7\27\1\103\13\27\2\0\1\67\5\27"+
    "\15\0\1\67\2\0\1\27\5\0\7\27\1\104\6\27"+
    "\1\105\4\27\2\0\1\67\5\27\15\0\1\67\2\0"+
    "\1\27\5\0\23\27\2\0\1\67\2\27\1\106\2\27"+
    "\17\0\1\107\60\0\1\110\60\0\1\111\60\0\1\112"+
    "\44\0\2\54\1\0\1\54\1\113\54\54\1\0\3\55"+
    "\1\56\2\0\37\55\3\0\5\55\2\0\1\55\14\0"+
    "\1\114\53\0\1\115\72\0\1\116\51\0\1\67\2\0"+
    "\1\27\5\0\3\27\1\117\17\27\2\0\1\67\5\27"+
    "\15\0\1\67\2\0\1\27\5\0\11\27\1\120\11\27"+
    "\2\0\1\67\5\27\15\0\1\67\2\0\1\27\5\0"+
    "\2\27\1\121\20\27\2\0\1\67\5\27\15\0\1\67"+
    "\2\0\1\27\5\0\17\27\1\122\3\27\2\0\1\67"+
    "\5\27\15\0\1\67\2\0\1\27\5\0\3\27\1\123"+
    "\17\27\2\0\1\67\5\27\15\0\1\67\2\0\1\27"+
    "\5\0\14\27\1\124\6\27\2\0\1\67\5\27\15\0"+
    "\1\67\2\0\1\27\5\0\20\27\1\125\2\27\2\0"+
    "\1\67\5\27\15\0\1\67\2\0\1\27\5\0\14\27"+
    "\1\126\6\27\2\0\1\67\5\27\15\0\1\67\2\0"+
    "\1\27\5\0\16\27\1\127\4\27\2\0\1\67\5\27"+
    "\15\0\1\67\2\0\1\27\5\0\4\27\1\130\16\27"+
    "\2\0\1\67\5\27\15\0\1\67\2\0\1\27\5\0"+
    "\10\27\1\131\12\27\2\0\1\67\5\27\15\0\1\67"+
    "\2\0\1\27\5\0\10\27\1\132\12\27\2\0\1\67"+
    "\5\27\15\0\1\67\2\0\1\27\5\0\23\27\2\0"+
    "\1\67\1\27\1\133\3\27\17\0\1\134\53\0\1\135"+
    "\65\0\1\136\53\0\1\137\63\0\1\67\2\0\1\27"+
    "\5\0\10\27\1\140\12\27\2\0\1\67\5\27\15\0"+
    "\1\67\2\0\1\27\5\0\11\27\1\141\11\27\2\0"+
    "\1\67\5\27\15\0\1\67\2\0\1\27\5\0\4\27"+
    "\1\142\16\27\2\0\1\67\5\27\15\0\1\67\2\0"+
    "\1\27\5\0\3\27\1\143\4\27\1\144\4\27\1\145"+
    "\4\27\1\146\2\0\1\67\5\27\15\0\1\67\2\0"+
    "\1\27\5\0\1\147\22\27\2\0\1\67\5\27\15\0"+
    "\1\67\2\0\1\27\5\0\6\27\1\150\14\27\2\0"+
    "\1\67\5\27\15\0\1\67\2\0\1\27\5\0\10\27"+
    "\1\151\12\27\2\0\1\67\5\27\15\0\1\67\2\0"+
    "\1\27\5\0\13\27\1\152\7\27\2\0\1\67\5\27"+
    "\15\0\1\67\2\0\1\27\5\0\11\27\1\153\11\27"+
    "\2\0\1\67\5\27\15\0\1\67\2\0\1\27\5\0"+
    "\20\27\1\154\2\27\2\0\1\67\5\27\15\0\1\67"+
    "\2\0\1\27\5\0\23\27\2\0\1\67\3\27\1\155"+
    "\1\27\15\0\1\67\2\0\1\27\5\0\2\27\1\156"+
    "\20\27\2\0\1\67\5\27\15\0\1\67\2\0\1\27"+
    "\5\0\1\157\22\27\2\0\1\67\5\27\15\0\1\67"+
    "\2\0\1\27\5\0\4\27\1\160\16\27\2\0\1\67"+
    "\5\27\15\0\1\67\2\0\1\27\5\0\5\27\1\161"+
    "\15\27\2\0\1\67\5\27\15\0\1\67\2\0\1\27"+
    "\5\0\16\27\1\162\4\27\2\0\1\67\5\27\15\0"+
    "\1\67\2\0\1\27\5\0\7\27\1\163\13\27\2\0"+
    "\1\67\5\27\15\0\1\67\2\0\1\27\5\0\20\27"+
    "\1\164\2\27\2\0\1\67\5\27\15\0\1\67\2\0"+
    "\1\27\5\0\16\27\1\165\4\27\2\0\1\67\5\27"+
    "\15\0\1\67\2\0\1\27\5\0\13\27\1\166\7\27"+
    "\2\0\1\67\5\27\15\0\1\67\2\0\1\27\5\0"+
    "\4\27\1\167\16\27\2\0\1\67\5\27\15\0\1\67"+
    "\2\0\1\27\5\0\4\27\1\170\16\27\2\0\1\67"+
    "\5\27\15\0\1\67\2\0\1\27\5\0\23\27\2\0"+
    "\1\67\1\170\4\27\15\0\1\67\2\0\1\27\5\0"+
    "\1\171\22\27\2\0\1\67\5\27\15\0\1\67\2\0"+
    "\1\27\5\0\16\27\1\172\4\27\2\0\1\67\5\27"+
    "\15\0\1\67\2\0\1\27\5\0\2\27\1\173\20\27"+
    "\2\0\1\67\5\27\15\0\1\67\2\0\1\27\5\0"+
    "\14\27\1\174\6\27\2\0\1\67\5\27\15\0\1\67"+
    "\2\0\1\27\5\0\10\27\1\175\12\27\2\0\1\67"+
    "\5\27\15\0\1\67\2\0\1\27\5\0\1\176\22\27"+
    "\2\0\1\67\5\27\15\0\1\67\2\0\1\27\5\0"+
    "\6\27\1\177\14\27\2\0\1\67\5\27\15\0\1\67"+
    "\2\0\1\27\5\0\16\27\1\200\4\27\2\0\1\67"+
    "\5\27\15\0\1\67\2\0\1\27\5\0\4\27\1\201"+
    "\16\27\2\0\1\67\5\27\15\0\1\67\2\0\1\27"+
    "\5\0\11\27\1\202\11\27\2\0\1\67\5\27\15\0"+
    "\1\67\2\0\1\27\5\0\6\27\1\203\14\27\2\0"+
    "\1\67\5\27\15\0\1\67\2\0\1\27\5\0\11\27"+
    "\1\204\11\27\2\0\1\67\5\27\15\0\1\67\2\0"+
    "\1\27\5\0\12\27\1\205\10\27\2\0\1\67\5\27"+
    "\15\0\1\67\2\0\1\27\5\0\3\27\1\206\17\27"+
    "\2\0\1\67\5\27\15\0\1\67\1\207\1\0\1\27"+
    "\5\0\23\27\2\0\1\67\5\27\15\0\1\67\2\0"+
    "\1\27\5\0\1\210\22\27\2\0\1\67\5\27\15\0"+
    "\1\67\2\0\1\27\5\0\16\27\1\211\4\27\2\0"+
    "\1\67\5\27\15\0\1\67\2\0\1\27\5\0\4\27"+
    "\1\212\16\27\2\0\1\67\5\27\15\0\1\67\1\213"+
    "\1\0\1\27\5\0\23\27\2\0\1\67\5\27\15\0"+
    "\1\67\2\0\1\27\5\0\4\27\1\214\16\27\2\0"+
    "\1\67\5\27\45\0\1\215\30\0\1\67\2\0\1\27"+
    "\5\0\16\27\1\216\4\27\2\0\1\67\5\27\15\0"+
    "\1\67\2\0\1\27\5\0\1\217\22\27\2\0\1\67"+
    "\5\27\45\0\1\220\30\0\1\67\2\0\1\27\5\0"+
    "\17\27\1\221\3\27\2\0\1\67\5\27\32\0\1\222"+
    "\43\0\1\67\2\0\1\27\5\0\4\27\1\223\16\27"+
    "\2\0\1\67\5\27\15\0\1\67\2\0\1\27\5\0"+
    "\12\27\1\224\10\27\2\0\1\67\5\27\32\0\1\225"+
    "\43\0\1\67\2\0\1\27\5\0\2\27\1\226\20\27"+
    "\2\0\1\67\5\27\30\0\1\227\45\0\1\67\1\230"+
    "\1\0\1\27\5\0\23\27\2\0\1\67\5\27\15\0"+
    "\1\67\1\231\1\0\1\27\5\0\23\27\2\0\1\67"+
    "\5\27\30\0\1\232\45\0\1\67\2\0\1\27\5\0"+
    "\21\27\1\233\1\27\2\0\1\67\5\27\46\0\1\234"+
    "\57\0\1\235\60\0\1\236\61\0\1\237\27\0\1\67"+
    "\2\0\1\27\5\0\4\27\1\240\16\27\2\0\1\67"+
    "\5\27\36\0\1\241\54\0\1\242\60\0\1\243\64\0"+
    "\1\244\37\0\1\67\2\0\1\27\5\0\13\27\1\245"+
    "\7\27\2\0\1\67\5\27\42\0\1\246\46\0\1\247"+
    "\60\0\1\250\72\0\1\251\33\0\1\67\2\0\1\27"+
    "\5\0\20\27\1\252\2\27\2\0\1\67\5\27\41\0"+
    "\1\253\65\0\1\254\60\0\1\255\53\0\1\256\34\0"+
    "\1\67\2\0\1\27\5\0\14\27\1\257\6\27\2\0"+
    "\1\67\5\27\36\0\1\260\60\0\1\261\64\0\1\262"+
    "\60\0\1\263\57\0\1\264\60\0\1\265\22\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[6713];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\3\1\2\11\1\1\3\11\4\1\1\11"+
    "\16\1\2\11\1\1\3\11\4\1\1\11\1\1\1\0"+
    "\1\11\1\0\1\1\2\0\4\11\1\0\17\1\4\0"+
    "\4\11\15\1\4\11\47\1\1\0\3\1\1\0\1\1"+
    "\1\0\2\1\1\0\1\1\1\0\2\1\1\0\1\1"+
    "\4\0\1\1\4\0\1\1\4\0\1\1\4\0\1\1"+
    "\1\11\2\0\1\11\1\1\4\0\2\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[181];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    /* Tabla de símbolos que se va cargando durante el análisis */
    private TablaSimbolos tabla = new TablaSimbolos();

    /* Línea donde se abrió el comentario en curso (para informar si no se cierra) */
    private int lineaComentario = 0;

    /* Aperturas de más dentro de un comentario anidado (niveles no permitidos) */
    private int nivelesExtra = 0;

    private static final int MAX_ENTERO = 32767;   /* entero de 16 bits */
    private static final int MAX_STRING = 30;      /* caracteres, sin contar las comillas */

    /* Posición donde empieza el comentario en curso */
    private int inicioComentario = 0;

    /* Rangos [inicio, fin) de los comentarios: los usa el editor para colorearlos */
    private java.util.List<int[]> comentarios = new java.util.ArrayList<int[]>();

    public TablaSimbolos getTabla() {
        return tabla;
    }

    public java.util.List<int[]> getComentarios() {
        return comentarios;
    }

    private Token token(String nombre) {
        return new Token(nombre, yytext(), yyline + 1, yycolumn + 1,
                (int) yychar, yylength(), false);
    }

    private Token error(String mensaje) {
        return new Token("ERROR", mensaje, yyline + 1, yycolumn + 1,
                (int) yychar, yylength(), true);
    }

    /* Comentario que llega al fin del archivo sin cerrarse */
    private Token comentarioSinCerrar() {
        comentarios.add(new int[] { inicioComentario, Integer.MAX_VALUE });
        return new Token("ERROR", "Comentario sin cerrar (abierto en esta línea)",
                lineaComentario, 1, inicioComentario, 3, true);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token siguienteToken() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            switch (zzLexicalState) {
            case COMENTARIO: {
              yybegin(YYINITIAL);
                                return comentarioSinCerrar();
            }  // fall though
            case 182: break;
            case COMENTARIO_ANIDADO: {
              yybegin(YYINITIAL);
                                return comentarioSinCerrar();
            }  // fall though
            case 183: break;
            default:
        return null;
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return error("Carácter no reconocido: " + yytext());
            }
          // fall through
          case 53: break;
          case 2:
            { /* se ignoran */
            }
          // fall through
          case 54: break;
          case 3:
            { return error("Constante string sin comilla de cierre: " + yytext());
            }
          // fall through
          case 55: break;
          case 4:
            { return token("PAREN_IZQ");
            }
          // fall through
          case 56: break;
          case 5:
            { return token("PAREN_DER");
            }
          // fall through
          case 57: break;
          case 6:
            { return token("OP_MULT");
            }
          // fall through
          case 58: break;
          case 7:
            { return token("OP_SUMA");
            }
          // fall through
          case 59: break;
          case 8:
            { return token("COMA");
            }
          // fall through
          case 60: break;
          case 9:
            { return token("OP_RESTA");
            }
          // fall through
          case 61: break;
          case 10:
            { return token("OP_DIV");
            }
          // fall through
          case 62: break;
          case 11:
            { String lexema = yytext();
                                java.math.BigInteger valor = new java.math.BigInteger(lexema);
                                if (valor.compareTo(java.math.BigInteger.valueOf(MAX_ENTERO)) > 0) {
                                    return error("Constante entera fuera de rango (máximo "
                                            + MAX_ENTERO + "): " + lexema);
                                }
                                tabla.agregarConstante("_" + lexema, "CTE_E", lexema, null);
                                return token("CTE_E");
            }
          // fall through
          case 63: break;
          case 12:
            { return token("PUNTO_Y_COMA");
            }
          // fall through
          case 64: break;
          case 13:
            { return token("OP_MENOR");
            }
          // fall through
          case 65: break;
          case 14:
            { return token("OP_MAYOR");
            }
          // fall through
          case 66: break;
          case 15:
            { tabla.agregarId(yytext());
                                return token("ID");
            }
          // fall through
          case 67: break;
          case 16:
            { return token("CORCHETE_IZQ");
            }
          // fall through
          case 68: break;
          case 17:
            { return token("CORCHETE_DER");
            }
          // fall through
          case 69: break;
          case 18:
            { return token("LLAVE_IZQ");
            }
          // fall through
          case 70: break;
          case 19:
            { return token("LLAVE_DER");
            }
          // fall through
          case 71: break;
          case 20:
            { /* se ignora */
            }
          // fall through
          case 72: break;
          case 21:
            { return token("OP_DISTINTO");
            }
          // fall through
          case 73: break;
          case 22:
            { String lexema = yytext();
                                String contenido = lexema.substring(1, lexema.length() - 1);
                                if (contenido.length() > MAX_STRING) {
                                    return error("Constante string demasiado larga ("
                                            + contenido.length() + " caracteres, máximo "
                                            + MAX_STRING + "): " + lexema);
                                }
                                tabla.agregarConstante("_" + contenido.replace(' ', '_'),
                                        "CTE_STR", contenido, Integer.valueOf(contenido.length()));
                                return token("CTE_STR");
            }
          // fall through
          case 74: break;
          case 23:
            { String lexema = yytext();
                                double valor = Double.parseDouble(lexema);
                                if (valor > Float.MAX_VALUE) {
                                    return error("Constante real fuera de rango (32 bits): " + lexema);
                                }
                                tabla.agregarConstante("_" + lexema, "CTE_F", lexema, null);
                                return token("CTE_F");
            }
          // fall through
          case 75: break;
          case 24:
            { return token("OP_DECL_TIPO");
            }
          // fall through
          case 76: break;
          case 25:
            { return token("OP_MENOR_IGUAL");
            }
          // fall through
          case 77: break;
          case 26:
            { return token("OP_IGUAL");
            }
          // fall through
          case 78: break;
          case 27:
            { return token("OP_MAYOR_IGUAL");
            }
          // fall through
          case 79: break;
          case 28:
            { return token("IF");
            }
          // fall through
          case 80: break;
          case 29:
            { return token("OR");
            }
          // fall through
          case 81: break;
          case 30:
            { return error("Constante string con caracteres no permitidos: " + yytext());
            }
          // fall through
          case 82: break;
          case 31:
            { return error("Cierre de comentario sin apertura: *//");
            }
          // fall through
          case 83: break;
          case 32:
            { lineaComentario = yyline + 1;
                                inicioComentario = (int) yychar;
                                nivelesExtra = 0;
                                yybegin(COMENTARIO);
            }
          // fall through
          case 84: break;
          case 33:
            { return token("OP_ASIGNACION");
            }
          // fall through
          case 85: break;
          case 34:
            { return token("AND");
            }
          // fall through
          case 86: break;
          case 35:
            { return token("INT");
            }
          // fall through
          case 87: break;
          case 36:
            { comentarios.add(new int[] { inicioComentario, (int) yychar + 3 });
                                yybegin(YYINITIAL);
            }
          // fall through
          case 88: break;
          case 37:
            { yybegin(COMENTARIO_ANIDADO);
            }
          // fall through
          case 89: break;
          case 38:
            { if (nivelesExtra > 0) {
                                    nivelesExtra--;
                                } else {
                                    yybegin(COMENTARIO);
                                }
            }
          // fall through
          case 90: break;
          case 39:
            { nivelesExtra++;
                                return error("Comentario anidado en más de un nivel");
            }
          // fall through
          case 91: break;
          case 40:
            { return token("ELSE");
            }
          // fall through
          case 92: break;
          case 41:
            { return token("THEN");
            }
          // fall through
          case 93: break;
          case 42:
            { return token("ENDIF");
            }
          // fall through
          case 94: break;
          case 43:
            { return token("FLOAT");
            }
          // fall through
          case 95: break;
          case 44:
            { return token("WHILE");
            }
          // fall through
          case 96: break;
          case 45:
            { return token("WRITE");
            }
          // fall through
          case 97: break;
          case 46:
            { return token("STRING");
            }
          // fall through
          case 98: break;
          case 47:
            { return token("ENDWHILE");
            }
          // fall through
          case 99: break;
          case 48:
            { return token("DECLARE_SECTION");
            }
          // fall through
          case 100: break;
          case 49:
            { return token("PROGRAM_SECTION");
            }
          // fall through
          case 101: break;
          case 50:
            { return token("APLICARDESCUENTO");
            }
          // fall through
          case 102: break;
          case 51:
            { return token("ENDDECLARE_SECTION");
            }
          // fall through
          case 103: break;
          case 52:
            { return token("ENDPROGRAM_SECTION");
            }
          // fall through
          case 104: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
